### ISSUE TITLE
Enable dashboard refresh

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet_operational_dashboards#102]
## Use Case

Grafana can refresh graphs every X seconds or never. Most dashboards from grafana.com have this enabled. It's disabled for the dashboards from puppet_operational_dashboards. Would it make sense to enable the refresh/is it disabled by default? I don't know what's the polling interval in telegraf, but I think it makes sense when grafana refreshes in the same time period.

## Describe the Solution You Would Like

Enable refreshes in the dashboards.

## Describe Alternatives You've Considered

I could enable it locally, but then the puppet agent overwrites it during each run, so I need to set the dashboards to unmanaged.

**Comment by MartyEwings** [comment]
hi @bastelfreak  raised internal case  https://tickets.puppetlabs.com/browse/SUP-3735  for this

**Comment by MartyEwings** [comment]
@bastelfreak  this was a small piece of work and solid good default do i ran up the PR
