### ISSUE TITLE
PluginVersion in JSON has to match grafana version?

### ISSUE THREAD

**Issue by rwaffen** [puppetlabs/puppet_operational_dashboards#112]
hi,

has the pluginVersion to match the grafana version? Grafana is pinned to 8.2.7 and we like to update it to 9.2.4. Have we then also to update these dashboards?

https://github.com/puppetlabs/puppet_operational_dashboards/blob/eb3188c7c2dc6e8c5759d8785b6391ff61481941/files/Puppetdb_performance.json#L131

**Comment by SimonHoenscheid** [comment]
The field is not documented in the JSON model, I am curious what happen when exporting the dashboard, but in general I would expect the value can be omitted.

**Comment by SimonHoenscheid** [comment]
@rwaffen I just checked this, exporting the dashboard, removing the plugin version everywhere and importing it under a new name works and nothing is breaking

**Comment by m0dular** [comment]
Thanks @SimonHoenscheid for checking.  I also tried upgrading Grafana to 9.2.4 and didn't see any issues, so I'll close this one out.
