### ISSUE TITLE
Support G1 GC Metrics

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppet_operational_dashboards#125]
## Use Case
After [SERVER-3217](https://tickets.puppetlabs.com/browse/SERVER-3217) got Implemented with the PE 2023.0 release [(Release Notes),](https://www.puppet.com/docs/pe/2023.0/release_notes_pe.html#enhancements-pe-x-0) the support for the different GC here is missing. Being one of the customers who already adopted this change ealier leaves us with empty charts.

## Describe the Solution You Would Like
Implement support

## Describe Alternatives You've Considered
none

**Comment by MartyEwings** [comment]
@m0dular do we have this in our pipeline already? i remember a discussion

**Comment by MartyEwings** [comment]
Ok so i think the blocker on this one is some sort of keychange in the influx repos we need to look at, then this will be good to go
