### ISSUE TITLE
By default cannot disable grafana repo management

### ISSUE THREAD

**Issue by iscb1962** [puppetlabs/puppet_operational_dashboards#140]
## Describe the Bug
The main init.pp file includes the puppet_operational_dashboards::profile::dashboards module - which has a parameter manage_grafana_repo which defaults to true.  For those with air gapped systems we need to be able to set this value to false.

## Expected Behavior
We need to have a parameter for the main module which allows this value to be passed via hiera, and for that value to be passed to puppet_operational_dashboards::profile::dashboards.

## Steps to Reproduce
Install a system using the module - its impossible to disable creation of the the grafana repo without changing the code.

## Environment
Puppet Operational Dashboards Version 1.9.0 
Puppet version 7.20
CentOS 7

## Additional Context
None

**Comment by MartyEwings** [comment]
Hi there!

Have you attempted the airgapped instructions here:

https://github.com/puppetlabs/puppet_operational_dashboards#note-on-air-gapped-environments

You should also be able to set any parameter via hiera that is in the profile classes

**Comment by iscb1962** [comment]
Yes I did follow the instructions on the air gapped system on the module - however they're not the complete story.

I thought I'd already tried to set it via puppet_operational_dashboards::profile::dashboards::manage_grafana_repo in hieradata - however I must have mis typed the name - it does actually work if you set that value ...  apologies.

I think the doc could do with an update (and also it would be useful to have a method to supply install options for the package install, for example we need to include an option to enable our local repo).   

I'm happy to close this off - let me know.   Thanks.

**Comment by m0dular** [comment]
Hi @iscb1962, most parameters related to Grafana repo management should be in the puppet/grafana module, such as setting a custom [repo_url](https://forge.puppet.com/modules/puppet/grafana/reference#repo_url).  If that option works for you, you should be able to allow the module to manage the repo and set this parameter in Hiera to point to your local mirror.

I do agree that the docs could be more detailed, including this use case that I didn't consider.  If you can think of any other information do you think would be useful, let me know and we can add it.

**Comment by tuxmea** [comment]
The setup of an additional local repository should not be part of this module.
I agree, that there should be some guidelines in the documentation (e.g. pointing to yum_repo, zypper_repo or akt::source).
It would increase module complexity drastically if parameters for local repos for different OS must be added (Deb, Yum, Zypper).

@iscb1962 are you OK to close this issue?

**Comment by m0dular** [comment]
I opened #165 that should resolve this.

**Comment by m0dular** [comment]
Resolved in #165
