### ISSUE TITLE
module shouldn't assume apt type is present

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppet_operational_dashboards#144]
The following commit makes an assumption that apt::source type is present in catalog
https://github.com/puppetlabs/puppet_operational_dashboards/commit/0e0ff2256f1019a95e4c73b5335878fb9a7bd2e6)
This is not the case in RHEL environment, for example, and manifest fails to compile

**Comment by vchepkov** [comment]
Yes it does. The reason you don't see it, you have puppetlabs/apt module in your environment, we don't

**Comment by m0dular** [comment]
Resolved by #145
