### ISSUE TITLE
Unable to use custom grafana port

### ISSUE THREAD

**Issue by rjd1** [puppetlabs/puppet_operational_dashboards#187]
## Describe the Bug
When grafana management is enabled and the port is not using the default value, the service gets stuck in a restart loop.

## Expected Behavior
The grafana service should run normally and stay up with a custom port. 

## Steps to Reproduce
Configure the grafana server to use a different http port and set the value in the dashboards profile class. E.g., include the main puppet_operational_dashboards class and add to hiera:

```
grafana::cfg:
  server:
    http_port: 8080
puppet_operational_dashboards::profile::dashboards::grafana_port: 8080
```

## Environment
 - Module Version: 2.0.0
 - Puppet Version: 7.13.1
 - Platform: Amazon Linux 2 (RHEL7)

## Additional Context
The problem is the default port is hard-coded in templates/grafana_wait.epp. So it isn't seen as listening and systemd just keeps restarting the service.

**Comment by m0dular** [comment]
Fixed in #188
