### ISSUE TITLE
Add ability to customize the values for 'address' and 'databases' in postgres.epp template

### ISSUE THREAD

**Issue by rjd1** [puppetlabs/puppet_operational_dashboards#203]
## Use Case
FOSS users need the ability to modify connection settings in the postgres telegraf input config. Currently, 'pe-puppetdb' is hard-coded for the DB. It may be necessary to also modify/specify some other things in the address URL, namely username, password, & SSL options .

## Describe the Solution You Would Like
Add new class parameters for customizing the address string and DB. I think that in order to maintain support for the `$postgres_hosts` array and multiple hosts, there should be a few new ones added for 'address' (i.e., can't just implement `$postgres_address`). So, add something like: `$postgres_username`, `$postgres_password`, `$postgres_ssl_options`, & `$postgres_database`. Then obviously update the template to use them.

## Describe Alternatives You've Considered
None

## Additional Context
This relates to 'Postgresql Performance' dashboard support for Open Source Puppet users.

**Comment by Aaronoftheages** [comment]
Hi @rjd1 

We'll investigate this issue and create a ticket for it during our next cycle.

Thanks

**Comment by m0dular** [comment]
I looked into this and came up with a solution, assuming you're using the `puppetlabs/puppetdb` module to manage postgres and have SSL enabled.  Using that approach, the only thing that needs to be changed in the template is the database name, `pe-puppetdb` to `puppetdb`.  The main change is to add code that manages the `telegraf` role and some grants.

Ideally, I think this should be limited to SSL connections like in PE.  We already use a copy of the Puppet certs for `telegraf` to talk to other services, and it's not much to add the same for postgres.  That makes the configuration simple and more in line with how PE does it, with a caveat that SSL needs to be enabled using the `puppetdb` module like [here](https://github.com/puppetlabs/puppetlabs-puppetdb/blob/main/README.md#enable-ssl-connections).  I suppose we could add some parameters or a connection string to override this, so let me know what you think @rjd1.  I don't have a sense of whether FOSS users typically turn on SSL for postgres.

**Comment by rjd1** [comment]
@m0dular  In our case, we do use the `puppetlabs/puppetdb` module, but only to manage the PuppetDB server itself. The Postgres DB runs on an AWS-managed RDS instance. SSL is enabled, but we don't really have control over the settings. We cannot use the Puppet certs here and so do need to be able to override that.

**Comment by m0dular** [comment]
You may be able to account for that if you set [puppet_ssl_cert_file](https://forge.puppet.com/modules/puppetlabs/puppet_operational_dashboards/reference#puppet_ssl_cert_file) along with `puppet_ssl_key_file` and `puppet_ssl_ca_file`.  Those are the certs that the Telegraf inputs use when they talk to the various services.  However, these are shared across all of the inputs, so it may break talking to Puppet server and PDB if you change those.

I played around with some of the auth methods for postgres, but it looks like it always requires a valid client cert when using SSL, which makes sense.  So at the moment I don't think there's a way to make this module work with a different set of certs for postgres and Puppet services.  I think making the postgres template more configurable is a good option to account for all of this.

**Comment by m0dular** [comment]
Could you share the `pg_hba.conf` entry for the user that Telegraf connects as?  I didn't know it were possible to have SSL and password auth at the same time.  I was trying to test `verify-ca`, but I think this option was added after Postgres 11 so it didn't work in my test environment.

**Comment by rjd1** [comment]
I can't actually access the config file because AWS doesn't provide access to the underlying host. But from what I've gathered the `pg_hba_file_rules` [view](https://www.postgresql.org/docs/current/view-pg-hba-file-rules.html) will provide this info. There's nothing specific for this user, it looks like this is the relevant line that applies to all:

 ```
line_number | type  |   database    | user_name  | address  | netmask | auth_method |  options  | error
-------------+-------+---------------+------------+----------+---------+-------------+-----------+-------
          14 | host  | {all}         | {all}      | all      |         | md5         |           |
```

This is running Postgres 12.14, BTW. Also we're not specifying any custom config options here, so it seems this is just the default for at least Postgres 12 on RDS.

**Comment by m0dular** [comment]
That looks like SSL isn't enabled for postgres, and that it accepts password auth for any database from any IP?  That would certainly work, but it's way more access than something like this would need.  We only give the `telegraf` user `CONNECT` to `pe-puppetdb` and the `pg_monitor` role for the internal postgres metrics, for example.

**Comment by rjd1** [comment]
It may not be explicitly requiring SSL in the config, but it is certainly enabled and being actively used. There are other methods to restrict network access and we similarly grant limited read access to just the actual DB in use for this.

At the end of the day, I think some flexibility for configuring the connection within the template would be useful. The specific Postgres setup isn't really at issue here, but please keep in mind the various possible infrastructure deployments and the fact that open source users are left on their own to set up this access. I have no problem with requiring SSL - everyone should really be using it - so long as the options are sufficiently configurable and not prohibitively tied to PE standards.

**Comment by m0dular** [comment]
Agreed, and I am working on a PR to make the entire connection string configurable.  The main things will be:

* Accepting an optional password
* Adding a new hash of connection params with the current defaults, e.g. `sslmode=verify-full`
* Setting the database to `puppetdb` or `pe-puppetdb` depending on platform

I also have a new FOSS profile class to configure the auth and grants for a `telegraf` user, optional if you want to manage it yourself.

My questions were mainly to clarify things because it's a complicated subject, not to say one approach or the other is better.  I can see how it came off that way, so apologies for that.  If I understand it correctly, the `sslmode` param is for the client to verify the server, so the Telegraf client verifying the identity of the postgres node in this case.  But the `host` entry in HBA rules would mean the server accepts any connection as long as the correct password is provided.  I guess it ultimately doesn't matter as long as we allow it to be configured appropriately.

**Comment by m0dular** [comment]
PR up in #206, let me know what you think

**Comment by rjd1** [comment]
Looks good to me, thank you!
