### ISSUE TITLE
toml gem detection assumes static version of the gem and that the class is deployed on Puppetserver

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/puppet_operational_dashboards#3]
if !file('/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/toml-rb-2.1.1/README.md') {

This failed to detect version 2.1.2 on my system

this also assumes this class is run on a Puppetserver node?

**Comment by MartyEwings** [comment]
I think we should require the gem as a dependency, and have a class on to deploy on the compilation servers

**Comment by jarretlavallee** [comment]
Should toml-rb be a `feature`?

**Comment by MartyEwings** [comment]
removed
