### ISSUE TITLE
influxdb class does not exist in influxdb module

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/puppet_operational_dashboards#4]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class influxdb (file: /etc/puppetlabs/code/environments/production/modules/puppet_operational_dashboards/manifests/init.pp, line: 33, column: 7) on node pe-node-96c87a-5.us-west1-a.c.customer-support-scratchpad.internal

should this be referring to the type?

**Comment by jarretlavallee** [comment]
It's missing from the dependencies in the metadata.json https://github.com/puppetlabs/puppet_operational_dashboards/blob/main/metadata.json#L10

**Comment by jarretlavallee** [comment]
My mistake. I thought https://github.com/puppetlabs/influxdb/pull/14 was merged.
