### ISSUE TITLE
/etc/telegraf/ca.pem seems to be created AFTER its required on first install

### ISSUE THREAD

**Issue by gavindidrichsen** [puppetlabs/puppet_operational_dashboards#58]
## Describe the Bug
The syslog is showing the telegraf service fails to start because it can't find the ``/etc/telegraf/ca.pem``

![image](https://user-images.githubusercontent.com/16652757/171131696-813a67d9-c7a4-4f73-af6b-57c3ed3e422f.jpeg)
￼
```
May 31 08:09:58 dashboard-3bbbab-0 systemd: Starting The plugin-driven server agent for reporting metrics into InfluxDB...
May 31 08:09:58 dashboard-3bbbab-0 telegraf: 2022-05-31T08:09:58Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: error parsing influxdb_v2 array, could not read certificate "/etc/telegraf/ca.pem": open /etc/telegraf/ca.pem: no such file or directory
May 31 08:09:58 dashboard-3bbbab-0 systemd: telegraf.service: main process exited, code=exited, status=1/FAILURE
May 31 08:09:58 dashboard-3bbbab-0 systemd: Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.
May 31 08:09:58 dashboard-3bbbab-0 systemd: Unit telegraf.service entered failed state.
May 31 08:09:58 dashboard-3bbbab-0 systemd: telegraf.service failed.
May 31 08:09:58 dashboard-3bbbab-0 puppet-agent[5181]: Systemd start for telegraf failed!
```                     
￼
And then later the ``/etc/telegraf/ca.pem`` is setup:

![image](https://user-images.githubusercontent.com/16652757/171131843-61044648-dce8-4f4d-a6ca-53af5c5a68e7.jpeg)

## Expected Behavior
The ``/etc/telegraf/ca.pem`` should be present before the telegraf service requires in

## Steps to Reproduce

I added the dashboard classification and then did ``puppet agent -t``

![image](https://user-images.githubusercontent.com/16652757/171132260-4c6c6892-8b2b-404d-af46-de4487f28082.png)

## Environment
 - Centos 7
 - PE 2021.6 environment (1 primary, 1 node which is the dashboard)

**Comment by m0dular** [comment]
Should be resolved by the SSL changes in #60 and #62.  Let me know if you still hit this.
