### ISSUE TITLE
Airgapped Systems can not install telegraf due to hard coded archive url

### ISSUE THREAD

**Issue by tuxmea** [puppetlabs/puppet_operational_dashboards#88]
## Describe the Bug
When running in an airgapped environment the main class fails, when managing telegraf due to hardcoded internet URL for telegraf archive loaction.

## Expected Behavior
I am able to provide an telegraf archive3 location to fetch the arcive from a local web server

## Steps to Reproduce
No internet connection, add puppet_operational_dashboards class

## Environment
Any

**Comment by MartyEwings** [comment]
We have a PR i think solves this, its blocked by some upstream work in a dependant module, does this solve this situation

https://github.com/puppetlabs/puppet_operational_dashboards/pull/75/files

**Comment by tuxmea** [comment]
@MartyEwings upstream telegraf was released with the required patches. #75 will fix this issue.
