### ISSUE TITLE
Add toggle for manage dashboard

### ISSUE THREAD

**Issue by zoojar** [puppetlabs/puppet_operational_dashboards#97]
## Use Case

_As a user I want to have only the telegraf agent managed along with auth to pe,
so that I can have pe infra nodes logging to a central influxdb,
and a dashboard that provides a centralised view of all pe servers in a single place._

Currently the module assumes infra agents intending to log to influxdb will host their own dashboard:
https://github.com/puppetlabs/puppet_operational_dashboards/blob/a89c556a6785d20219d85ad029cffc506af1d26c/manifests/init.pp#L126-L132

## Describe the Solution You Would Like
add a feature toggle for the dashboards profile somewhere.
## Describe Alternatives You've Considered
Managing with a profile wrapper and hiera data:

```
# dashboard_agent.pp
    if $agent_only {
      include 'puppet_operational_dashboards::telegraf::agent'
    } else {
      include puppet_operational_dashboards
    }
```

```
# common.yaml
profile::dashboard::agent_only: true
puppet_operational_dashboards::manage_influxdb: false
puppet_operational_dashboards::manage_telegraf_token: false
puppet_operational_dashboards::profile::dashboards::manage_grafana: false
```

```
# roles/dashboard.yaml
profile::dashboard::agent_only: false
puppet_operational_dashboards::manage_influxdb: true
puppet_operational_dashboards::profile::dashboards::manage_grafana: true
puppet_operational_dashboards::manage_telegraf_token: true
puppet_operational_dashboards::telegraf_token: ~
lookup_options:
  puppet_operational_dashboards::telegraf::agent::token:
    convert_to: "Undef"
puppet_operational_dashboards::telegraf::agent::token: ~
```

**Comment by MartyEwings** [comment]
hi @zoojar 

Is this not infact how it currently works?

As it stands we classify all infrastructure nodes with the class:

puppet_operational_dashboards::enterprise_infrastructure, this does the authorisation and shipping of the data to a singular influxdb data source

and then we select a singular node to be the grafana host which views the common influxdb data source all the infrastructure nodes ship too:

by adding the class:

puppet_operational_dashboards

**Comment by zoojar** [comment]
hi  @MartyEwings  thank you! I re-think this!
